# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jtao9AJaSUIqLz8DxC_0avSRs7SE49Tv
"""

# -*- coding: utf-8 -*-
"""
Системно-динамическая модель транспортной системы города.
Версия 2.1 (May 2026) — patched for structural validation and stronger
behaviour reproduction of Downs–Thomson.

State vector y (14 stocks):
  y[0]=POP, y[1]=GRP, y[2]=EMP, y[3]=PARK, y[4]=UA, y[5]=COWN,
  y[6]=EV, y[7]=AV, y[8]=V2X, y[9]=MAAS,
  y[10]=PT_cap, y[11]=GridCap, y[12]=CULT, y[13]=TRAV
"""

import math
import numpy as np
from scipy.integrate import solve_ivp

# ─── ПАРАМЕТРЫ ───────────────────────────────────────────────────────────────
P = dict(
    # Население
    alpha_POP=0.010, eta_POP_EMP_in=0.45, delta_POP=0.008,
    eta_POP_AQ=0.20, eta_POP_EMP_out=0.35, POP_max=10.0,

    # WFH
    WFH_min=0.05, WFH_max=0.30, r_WFH=0.08,

    # Доход
    IncomeShare_base=0.60, IncomeShare_trend=0.001,

    # ВРП
    alpha_GRP=40.56, GRP_max=250.0,
    beta_ACC=1.15, ValueOfTime=20.0, beta_AQ=0.03, CostPerAccident=0.5,

    # Занятость
    alpha_EMP=0.05, eta_EMP_GRP=0.40, eta_EMP_POP=0.35, delta_EMP=0.05, EMP_max=5.0,

    # E-commerce
    ECOM_max=0.30, ECOM_base=0.10, eta_ECOM_GRP=0.70,
    alpha_ECOM_WFH=0.50, beta_ECOM_CONG=0.20,

    # Land Use
    alpha_UA=0.0003, beta_UA_ACC=0.35, beta_WFH_UA=0.20, beta_AV_UA=0.15, delta_UA=0.010,
    alpha_PARK=1.2, delta_PARK=0.02,

    # Спрос
    CommuteTripRate=2.0, OtherTripRate=2.2, TL_base=14.0,
    BasePeak=0.15, EcomPeakSmooth=0.07,
    Occ_A=1.4, EmptyRate=0.40, BusKmFactor=0.10,
    CruisingFraction=0.15, AvgDelivDist=5.0, DelivFactor=1.5, RepositionRatio=0.15,

    # Логит-функция модального выбора
    mu=0.07, beta_t=0.05, beta_c=0.03,
    delta_own=0.20, gamma_cult=0.10, gamma_hab=0.10, delta_road=0.02,
    kappa_crowd=1.20, beta_maas=0.10, delta_infra_PT=0.22, WFH_PT_coeff=0.45,
    gamma_maas=0.10, BK_speed_base=17.0, kappa_acc=0.20, delta_infra_bk=0.20,
    SafetyCoeff=0.25, MS_BK_base=0.05,

    # Дорожная сеть
    Physical_cap_base=18.0, CapPerDollar=0.30, SpaceReallocRate=0.02,
    # Насыщающая отдача дорожных инвестиций (Downs-Thomson / Duranton-Turner 2011):
    # gamma_road = макс. абсолютный прирост RCAP от дорожных инвестиций (ед. RCAP),
    # K_road = полунасыщение по TINV_road.
    gamma_road=0.30, K_road=1.0,
    FF_speed_base=45.0, V2X_delay_factor=0.15,
    FF_speed_PT_base=25.0, BusLane=0.0, BusLane_bonus=0.22,
    V2X_PT_bonus=0.07, WaitTime_base=7.0, WaitCoeff=6.0,
    PT_capacity_max=5.0, PT_lifetime=27.0, CapacityPerDollar=0.80,
    alpha_auto=0.60, alpha_pt=0.45, alpha_rh=0.30,
    DENS_crit=15000.0, gamma_dens=1.0,
    TT_A_base=25.0, TT_PT_base=35.0, TT_RH_base=28.0,
    AV_PT_bonus=0.12, CrowdCoeff=3.0,

    # Автопарк
    V_sat_COWN=600.0, alpha_COWN=-1.810, beta_COWN=-0.08,
    eta_COWN_DENS=-0.45, eta_COWN_PARK=0.20,
    OccTarget=0.85, tau_COWN_buy=3.0, tau_COWN_retire=12.0, tau_COWN_shed=5.0,
    lambda_COWN_MAAS=0.03, beta_CULT_buy=0.20, beta_CULT_shed=0.20,
    p_EV=0.005, q_EV=0.35, eta_EV_INC=1.0, delta_EV=0.07,
    p_AV=0.002, q_AV=0.30, delta_AV=0.07,
    alpha_V2X=0.03, delta_V2X=0.07,
    p_MAAS=0.01, q_MAAS=0.20, MAAS_market_potential=0.4, churn_MAAS=0.15,
    AV_robo_threshold=0.12, AVaversion_coeff=0.30, AVaversion_base=0.20,

    # Финансы
    Budget_share_GRP=0.02,
    Budget_pressure_sensitivity=0.50, Budget_pressure_scale=0.5,
    share_PT_base=0.40, share_road_base=0.30,
    share_digital_base=0.10, share_bike_base=0.10, share_GRID_base=0.10,
    eta_share_PT_AQ=0.20, eta_share_road_AQ=-0.15, eta_share_road_CO2=-0.15,
    eta_share_digital_AQ=0.10, k_CO2digital=0.30,
    eta_share_bike_AQ=0.15, eta_share_bike_CO2=0.10, eta_share_GRID=0.50,
    PT_opex_base=0.8, Fixed_opex_share=0.50, Variable_opex_share=0.50,
    PT_subsidy_base=0.3, Subsidy_deficit_coverage=0.60, Reinvestable_share_PT=0.50,
    Charge_rate=0.0,

    # Доп. параметры для behaviour reproduction
    FreezePolicyShares=0,
    pt_policy_multiplier=1.0,
    road_policy_multiplier=1.0,
    lambda_buslane_PT=0.25,
    BusCongestionFactor=0.35,

    # Экология
    AQ_base=50.0, alpha_vmt=0.003, EV_local_clean=0.80, alpha_cong=0.02,
    BaseAccRate=1.2, AV_safety_gain=0.45, V2X_safety_gain=0.20,
    EF_ICE=150.0, EF_grid_per_km=80.0, PT_elec=0.50,
    CO2_base=6.0, CO2_target=5.0,

    # Энергосеть
    BaseLoad=2.0, AvgConsumption=5.0, SmartChargeAdjust=0.75,
    DeprRate_Grid=0.03, CapacityPerDollar_Grid=0.60,

    # Поведение
    HABM_base=0.50, beta_HABM_MAAS=0.03,
    alpha_CULT=0.20, delta_CULT=0.03,
    alpha_TRAV_AV=0.03, alpha_TRAV_MAAS=0.03, alpha_TRAV_REG=0.05,
    alpha_TRAV_MEDIA=0.03, beta_TRAV_ACC=0.30, beta_TRAV_MEDIA=0.12,

    # Экзогенные
    Regulation_quality=0.50, Media_tone=0.10, ClimateWill=0.50,
    SpeedLimit=60.0, SpeedLimit_base=60.0,
    ParkCost=2.0, WaitBase=6.0, FarePT=1.0,
    FareRH_base=5.0, AV_cost_reduction=0.40, EV_cost_discount=0.07,
    RH_lane_penalty=0.10, RH_lane_access=0.0,
    delta_lastmile=0.20, TINV_bike_base=0.2, TINV_road_base=0.5, TINV_PT_base=0.5,
    GRID_base=1.0,

    # Базовые значения нормировки
    EMP_base=0.9, GRP_base=40.0, POP_base=2.0, DENS_base=4000.0,
    ACC_jobs_base=1.0, INC_base=12.0, UrbanArea_base=500.0,
    PARK_eff_base=0.85, PT_capacity_base=1.0, ACC_R_base=1.2, COWN_base=200.0,
)

STOCKS = [
    "POP", "GRP", "EMP", "PARK", "UA", "COWN",
    "EV", "AV", "V2X", "MAAS",
    "PT_cap", "GridCap", "CULT", "TRAV"
]


def initial_state():
    return np.array([
        2.0,    # POP
        40.0,   # GRP
        0.9,    # EMP
        300.0,  # PARK
        500.0,  # UA
        300.0,  # COWN
        0.05,   # EV
        0.0,    # AV
        0.0,    # V2X
        0.05,   # MAAS
        1.0,    # PT_cap
        5.0,    # GridCap
        0.5,    # CULT
        0.3,    # TRAV
    ], dtype=float)


EP = 1e-9


def sp(b, e):
    if b > 0:
        return b ** e
    return 0.0


def c01(x):
    return max(0.0, min(1.0, x))


def compute_aux(t, y, params, n_iter=4):
    P = params

    POP, GRP, EMP, PARK, UA, COWN, EV, AV, V2X, MAAS, PT_cap, GridCap, CULT, TRAV = y
    POP = max(POP, 0.1)
    GRP = max(GRP, 0.5)
    EMP = max(EMP, 0.01)
    PARK = max(PARK, 1.0)
    UA = max(UA, 10.0)
    COWN = max(COWN, 1.0)
    EV = c01(EV)
    AV = c01(AV)
    V2X = c01(V2X)
    MAAS = max(MAAS, 0.0)
    PT_cap = max(PT_cap, 0.01)
    GridCap = max(GridCap, 0.1)
    CULT = c01(CULT)
    TRAV = c01(TRAV)

    a = {}

    # ── Базовые ──
    a["WFH"] = P["WFH_min"] + (P["WFH_max"] - P["WFH_min"]) * (1 - math.exp(-P["r_WFH"] * t))
    a["INC"] = GRP * (P["IncomeShare_base"] + P["IncomeShare_trend"] * t) / (POP + EP)
    a["DENS"] = POP * 1e6 / (UA + EP)
    a["DensPen"] = (
        1.0 if a["DENS"] <= P["DENS_crit"]
        else math.exp(-P["gamma_dens"] * (a["DENS"] - P["DENS_crit"]) / P["DENS_crit"])
    )
    a["FF_spd"] = P["FF_speed_base"] * sp(P["DENS_base"] / (a["DENS"] + EP), 0.15)
    a["TL"] = (
        P["TL_base"]
        * sp(P["DENS_base"] / (a["DENS"] + EP), 0.25)
        * (1 + a["WFH"] * 0.15)
        * (1 + AV * 0.20)
    )
    a["HABM"] = P["HABM_base"] / (1 + P["beta_HABM_MAAS"] * MAAS)
    a["TrustBarrier"] = (
        (1 - TRAV) * P["AVaversion_coeff"] if AV > P["AV_robo_threshold"]
        else P["AVaversion_base"]
    )
    a["PARK_eff"] = min(1.0, PARK / (COWN * POP / (P["OccTarget"] + EP) + EP))

    # COWN_desired: Gompertz
    gomp_INC = math.exp(P["alpha_COWN"] * math.exp(P["beta_COWN"] * a["INC"]))
    a["COWN_des"] = (
        P["V_sat_COWN"] * gomp_INC
        * sp(max(a["DENS"], 1.0) / P["DENS_base"], P["eta_COWN_DENS"])
        * sp(a["PARK_eff"] / P["PARK_eff_base"], P["eta_COWN_PARK"])
    )

    a["FareRH"] = (
        P["FareRH_base"]
        * (1 - AV * P["AV_cost_reduction"])
        * (1 - EV * P["EV_cost_discount"])
    )
    wait_rh = P["WaitBase"] * (1 - AV * 0.3)
    a["TT_RH_const_part"] = wait_rh

    # ── Начальная инициализация инвестиций ──
    TINV_common = max(P["Budget_share_GRP"] * GRP, 0.05)

    init_sPT = P["share_PT_base"] * P.get("pt_policy_multiplier", 1.0)
    init_sR = P["share_road_base"] * P.get("road_policy_multiplier", 1.0)
    init_sD = P["share_digital_base"]
    init_sB = P["share_bike_base"]
    init_sG = P["share_GRID_base"]

    init_sum = init_sPT + init_sR + init_sD + init_sB + init_sG + EP

    a["TINV_PT"] = TINV_common * init_sPT / init_sum
    a["TINV_road"] = TINV_common * init_sR / init_sum
    a["TINV_digital"] = TINV_common * init_sD / init_sum
    a["TINV_bike"] = TINV_common * init_sB / init_sum
    a["TINV_GRID"] = TINV_common * init_sG / init_sum
    a["TINV_common"] = TINV_common

    # ── Начальные оценки циклических переменных ──
    a["CONG"] = 0.3
    a["VMT"] = 30.0
    a["EffRoadVMT"] = 30.0
    a["MS_A"] = 0.5
    a["MS_PT"] = 0.25
    a["MS_RH"] = 0.1
    a["MS_BK"] = 0.05
    a["MS_W"] = 0.1
    a["PTCR"] = 0.5
    a["BusLane_eff"] = P["BusLane"]

    for _ in range(n_iter):
        # ECOM
        a["ECOM"] = min(
            P["ECOM_max"],
            P["ECOM_base"] * sp(GRP / (P["GRP_base"] + EP), P["eta_ECOM_GRP"])
            * (1 + P["alpha_ECOM_WFH"] * a["WFH"])
            / (1 + P["beta_ECOM_CONG"] * a["CONG"])
        )

        # TRIPS, PEAK
        a["TRIPS"] = (
            EMP * (1 - a["WFH"]) * P["CommuteTripRate"]
            + POP * P["OtherTripRate"] * sp(a["INC"] / (P["INC_base"] + EP), 0.15) * (1 - a["ECOM"] * 0.07)
        )
        a["PEAK"] = (
            P["BasePeak"] * (1 - a["WFH"] * 0.6)
            * (1 - a["ECOM"] * P["EcomPeakSmooth"])
            * sp(EMP / P["EMP_base"], 0.3)
        )

        # RCAP
        v2x_cap = V2X * 0.15 if V2X > 0.2 else 0.0
        # Насыщающая отдача дорожных инвестиций: первые вложения эффективны,
        # дальнейшие дают убывающий прирост ёмкости (Duranton & Turner 2011).
        # Это восстанавливает сильную форму Downs-Thomson: новая ёмкость
        # почти полностью поглощается индуцированным спросом.
        road_cap_add = (
            P["gamma_road"] * a["TINV_road"]
            / (a["TINV_road"] + P["K_road"] + EP)
        )
        a["RCAP"] = max(
            P["Physical_cap_base"]
            * sp(P["DENS_base"] / (a["DENS"] + EP), 0.12)
            * (1 + v2x_cap)
            * (1 + AV * 0.20)
            + road_cap_add
            - a["TINV_PT"] * P["SpaceReallocRate"],
            1.0,
        )

        # TT_A
        a["TT_A"] = max(
            (a["TL"] / (a["FF_spd"] + EP)) * 60
            * (1 + 0.15 * (1 - V2X * P["V2X_delay_factor"]) * a["CONG"] ** 4),
            1.0,
        )

        # PT loading and TT_PT
        a["PTCR"] = max(
            a["TRIPS"] * a["MS_PT"] * a["PEAK"] / (PT_cap + EP) * (1 + AV * P["AV_PT_bonus"]),
            0.0,
        )

        crowd_excess = max(0.0, a["PTCR"] - 0.85)
        crowd_wait = crowd_excess * P["WaitCoeff"]

        a["BusLane_eff"] = min(
            1.0,
            P["BusLane"] + P["lambda_buslane_PT"] * a["TINV_PT"] / (P["TINV_PT_base"] + EP)
        )

        pt_speed = (
            P["FF_speed_PT_base"]
            * (1 + a["BusLane_eff"] * P["BusLane_bonus"])
            * (1 + V2X * P["V2X_PT_bonus"])
        )

        a["TT_PT"] = max(
            (a["TL"] / (pt_speed + EP)) * 60 * (1 + 0.20 * crowd_excess)
            + P["WaitTime_base"] * (P["PT_capacity_base"] / (PT_cap + EP)) * (1 + crowd_wait),
            1.0,
        )

        a["TT_RH"] = a["TT_A"] + a["TT_RH_const_part"]

        # Last-mile / crowd
        LMB = (
            P["delta_lastmile"]
            * (a["MS_BK"] / (P["MS_BK_base"] + EP))
            * (a["TINV_bike"] / (P["TINV_bike_base"] + EP))
        )
        CrowdPen = crowd_excess * P["CrowdCoeff"]

        # Utilities
        U_A = (
            P["beta_t"] * a["TT_A"]
            + P["beta_c"] * P["ParkCost"] / (a["INC"] / P["INC_base"] + EP)
            - P["delta_own"] * COWN / (COWN + P["COWN_base"] + EP)
            - P["gamma_cult"] * CULT
            - P["gamma_hab"] * a["HABM"]
            - P["delta_road"] * a["TINV_road"] / (P["TINV_road_base"] + EP)
        )

        U_PT = (
            P["beta_t"] * a["TT_PT"]
            + P["beta_c"] * P["FarePT"] / (a["INC"] / P["INC_base"] + EP)
            - P["beta_maas"] * MAAS
            + P["kappa_crowd"] * CrowdPen
            + P["gamma_hab"] * a["HABM"]
            - P["delta_infra_PT"] * a["TINV_PT"] / (P["TINV_PT_base"] + EP)
            - LMB
            + P["WFH_PT_coeff"] * a["WFH"] * (1 - a["WFH"])
        )

        U_RH = (
            P["beta_t"] * a["TT_RH"]
            + P["beta_c"] * a["FareRH"] / (a["INC"] / P["INC_base"] + EP)
            + P["gamma_hab"] * a["HABM"]
            - P["gamma_maas"] * MAAS / (P["MAAS_market_potential"] + EP)
            + a["TrustBarrier"]
        )

        U_BK = (
            P["beta_t"] * (a["TL"] / P["BK_speed_base"]) * 60 * sp(P["DENS_base"] / (a["DENS"] + EP), 0.15)
            + P["gamma_hab"] * a["HABM"]
            + P["kappa_acc"] * a["MS_A"]
            - P["delta_infra_bk"] * a["TINV_bike"] / (P["TINV_bike_base"] + EP)
            - P["SafetyCoeff"] * sp(a["MS_BK"] / (P["MS_BK_base"] + EP), 0.6)
        )

        U_W = math.exp(-1.5 / (a["TL"] + EP))

        exps = np.clip(
            np.exp(-P["mu"] * np.array([U_A, U_PT, U_RH, U_BK, U_W])),
            1e-20, 1e20
        )
        sm = exps.sum()
        a["MS_A"], a["MS_PT"], a["MS_RH"], a["MS_BK"], a["MS_W"] = exps / sm

        # VMT / CONG
        AutoVMT = a["TRIPS"] * a["TL"] * a["MS_A"] / P["Occ_A"]
        RHVMT = a["TRIPS"] * a["TL"] * a["MS_RH"] * (1 + P["EmptyRate"])
        PTVMT = a["TRIPS"] * a["TL"] * a["MS_PT"] * P["BusKmFactor"]
        park_r = PARK / (COWN * POP / (P["OccTarget"] + EP) + EP)
        CruisVMT = a["TRIPS"] * a["MS_A"] * P["CruisingFraction"] * max(0.0, 1 - park_r) ** 1.5
        DelivVMT = a["ECOM"] * P["AvgDelivDist"] * P["DelivFactor"]
        ReposVMT = AV * a["TRIPS"] * a["MS_A"] * P["RepositionRatio"]

        a["VMT"] = max(
            AutoVMT + RHVMT + PTVMT + DelivVMT + CruisVMT + ReposVMT,
            0.1,
        )

        a["EffRoadVMT"] = max(
            AutoVMT
            + RHVMT
            + P["BusCongestionFactor"] * PTVMT
            + DelivVMT
            + CruisVMT
            + ReposVMT,
            0.1,
        )

        a["CONG"] = max(a["EffRoadVMT"] * a["PEAK"] / (a["RCAP"] + EP), 0.01)

        a["AutoVMT"] = AutoVMT
        a["PTVMT"] = PTVMT

        # AQ / CO2
        a["EV_gen"] = c01((EV * AutoVMT + P["PT_elec"] * PTVMT) / (a["VMT"] + EP))
        a["AQ"] = (
            P["AQ_base"]
            + P["alpha_vmt"] * a["VMT"] * (1 - P["EV_local_clean"] * a["EV_gen"])
            + P["alpha_cong"] * a["CONG"]
        )
        a["CO2"] = (
            a["VMT"] * 365
            * ((1 - a["EV_gen"]) * P["EF_ICE"] + a["EV_gen"] * P["EF_grid_per_km"])
            / 1e6
        )

        # PT finance
        FREV_fare = a["TRIPS"] * a["MS_PT"] * P["FarePT"]
        PT_opex = P["PT_opex_base"] * (
            P["Fixed_opex_share"] + P["Variable_opex_share"] * PT_cap / P["PT_capacity_base"]
        )
        PT_sub = P["PT_subsidy_base"] + P["Subsidy_deficit_coverage"] * max(0.0, PT_opex - FREV_fare)
        a["FREV"] = FREV_fare + PT_sub

        PT_gap = max(0.0, PT_opex - a["FREV"])
        Bud_press = PT_gap / (PT_gap + P["Budget_pressure_scale"] + EP)
        a["TINV_common"] = max(
            P["Budget_share_GRP"] * GRP * (1 - P["Budget_pressure_sensitivity"] * Bud_press),
            0.05,
        )

        # GRID
        ev_kw = EV * (COWN * POP) * P["AvgConsumption"] * a["PEAK"] * P["SmartChargeAdjust"] / 1000.0
        a["GRID"] = (P["BaseLoad"] + ev_kw) / (GridCap + EP)

        aq_r = a["AQ"] / (P["AQ_base"] + EP)
        co2_r = a["CO2"] / (P["CO2_base"] + EP)

        base_sPT = P["share_PT_base"] * P.get("pt_policy_multiplier", 1.0)
        base_sR = P["share_road_base"] * P.get("road_policy_multiplier", 1.0)
        base_sD = P["share_digital_base"]
        base_sB = P["share_bike_base"]
        base_sG = P["share_GRID_base"]

        if P.get("FreezePolicyShares", 0):
            sPT = base_sPT
            sR = base_sR
            sD = base_sD
            sB = base_sB
            sG = base_sG
        else:
            sPT = base_sPT * sp(aq_r, P["eta_share_PT_AQ"])
            sR = base_sR * sp(aq_r, P["eta_share_road_AQ"]) * sp(co2_r, P["eta_share_road_CO2"])
            sD = base_sD * (1 + P["k_CO2digital"] * max(0.0, a["CO2"] / (P["CO2_target"] + EP) - 1))
            sB = base_sB * sp(aq_r, P["eta_share_bike_AQ"]) * sp(co2_r, P["eta_share_bike_CO2"])
            sG = base_sG * sp(a["GRID"] / (P["GRID_base"] + EP), P["eta_share_GRID"])

        sS = sPT + sR + sD + sB + sG + EP
        PT_surplus = P["Reinvestable_share_PT"] * max(0.0, a["FREV"] - PT_opex)

        a["TINV_PT"] = a["TINV_common"] * sPT / sS + PT_surplus
        a["TINV_road"] = a["TINV_common"] * sR / sS
        a["TINV_digital"] = a["TINV_common"] * sD / sS
        a["TINV_bike"] = a["TINV_common"] * sB / sS
        a["TINV_GRID"] = a["TINV_common"] * sG / sS

    # ── Финальные переменные ──
    a["ACC_jobs"] = (
        P["ACC_jobs_base"] * a["DensPen"]
        * sp(P["TT_A_base"] / (a["TT_A"] + EP), P["alpha_auto"])
        * sp(P["TT_PT_base"] / (a["TT_PT"] + EP), P["alpha_pt"])
        * sp(P["TT_RH_base"] / (a["TT_RH"] + EP), P["alpha_rh"])
    )

    a["ACC_R"] = (
        P["BaseAccRate"]
        * (1 - AV * P["AV_safety_gain"])
        * (1 - V2X * P["V2X_safety_gain"])
    )

    a["GRP_in"] = max(
        0.0,
        P["alpha_GRP"] * EMP
        * sp(max(a["ACC_jobs"], 0.01), P["beta_ACC"])
        * a["DensPen"]
        * sp(a["DENS"] / (P["DENS_base"] + EP), 0.15)
        * (1 - GRP / (P["GRP_max"] + EP))
    )

    delay_h = max(0.0, a["TT_A"] / 60 - a["TL"] / (a["FF_spd"] + EP))
    a["GRP_out"] = max(
        POP * P["ValueOfTime"] * delay_h * a["TRIPS"] / P["POP_base"] * 0.001
        + P["beta_AQ"] * max(0.0, a["AQ"] - P["AQ_base"])
        + a["ACC_R"] * P["CostPerAccident"],
        0.0
    )

    return a


def f(t, y, params):
    P = params
    POP, GRP, EMP, PARK, UA, COWN, EV, AV, V2X, MAAS, PT_cap, GridCap, CULT, TRAV = y

    POP_s = max(POP, 0.1)
    GRP_s = max(GRP, 0.5)
    EMP_s = max(EMP, 0.01)
    PARK_s = max(PARK, 1.0)
    UA_s = max(UA, 10.0)
    COWN_s = max(COWN, 1.0)
    EV_s = c01(EV)
    AV_s = c01(AV)
    V2X_s = c01(V2X)
    MAAS_s = max(MAAS, 0.0)
    PT_cap_s = max(PT_cap, 0.01)
    GridCap_s = max(GridCap, 0.1)
    CULT_s = c01(CULT)
    TRAV_s = c01(TRAV)

    a = compute_aux(t, y, P)

    POP_in = (
        P["alpha_POP"] * POP_s
        * sp(EMP_s / (P["EMP_base"] + EP), P["eta_POP_EMP_in"])
        * (1 - POP_s / P["POP_max"])
    )
    POP_out = (
        P["delta_POP"] * POP_s
        * sp(a["AQ"] / (P["AQ_base"] + EP), P["eta_POP_AQ"])
        * sp(P["EMP_base"] / (EMP_s + EP), P["eta_POP_EMP_out"])
    )
    dPOP = POP_in - POP_out

    dGRP = a["GRP_in"] - a["GRP_out"]

    EMP_in = (
        P["alpha_EMP"] * EMP_s
        * sp(GRP_s / (P["GRP_base"] + EP), P["eta_EMP_GRP"])
        * sp(POP_s / (P["POP_base"] + EP), P["eta_EMP_POP"])
        * (1 - EMP_s / (P["EMP_max"] + EP))
    )
    EMP_out = P["delta_EMP"] * EMP_s
    dEMP = EMP_in - EMP_out

    UA_in = (
        P["alpha_UA"] * POP_s
        * sp(max(a["ACC_jobs"], 0.01), P["beta_UA_ACC"])
        * (1 + P["beta_WFH_UA"] * a["WFH"] + P["beta_AV_UA"] * AV_s)
    )
    UA_out = P["delta_UA"] * UA_s
    dUA = UA_in - UA_out

    COWN_in = max(0.0, (a["COWN_des"] - COWN_s) / P["tau_COWN_buy"]) * (1 + P["beta_CULT_buy"] * CULT_s)
    COWN_out = (
        COWN_s / P["tau_COWN_retire"]
        + P["lambda_COWN_MAAS"] * COWN_s * (MAAS_s / (P["MAAS_market_potential"] + EP))
        + max(0.0, (COWN_s - a["COWN_des"]) / P["tau_COWN_shed"]) * (1 - P["beta_CULT_shed"] * CULT_s)
    )
    dCOWN = COWN_in - COWN_out

    PARK_in = P["alpha_PARK"] * COWN_in
    PARK_out = P["delta_PARK"] * PARK_s
    dPARK = PARK_in - PARK_out

    EV_in = (
        (P["p_EV"] + P["q_EV"] * EV_s)
        * (1 - EV_s)
        * sp(a["INC"] / (P["INC_base"] + EP), P["eta_EV_INC"])
    )
    EV_out = P["delta_EV"] * EV_s * a["GRID"]
    dEV = EV_in - EV_out

    AV_in = (P["p_AV"] + P["q_AV"] * AV_s) * (1 - AV_s) * (1 - a["TrustBarrier"])
    AV_out = P["delta_AV"] * AV_s
    dAV = AV_in - AV_out

    V2X_in = P["alpha_V2X"] * a["TINV_digital"] * (1 - V2X_s)
    V2X_out = P["delta_V2X"] * V2X_s
    dV2X = V2X_in - V2X_out

    MAAS_in = max(
        0.0,
        (P["p_MAAS"] + P["q_MAAS"] * MAAS_s / (P["MAAS_market_potential"] + EP))
        * (1 - a["HABM"])
        * (P["MAAS_market_potential"] - MAAS_s)
    )
    MAAS_out = P["churn_MAAS"] * MAAS_s
    dMAAS = MAAS_in - MAAS_out

    PTcap_in = a["TINV_PT"] * P["CapacityPerDollar"] * (1 - PT_cap_s / (P["PT_capacity_max"] + EP))
    PTcap_out = PT_cap_s / P["PT_lifetime"]
    dPT_cap = PTcap_in - PTcap_out

    Grid_in = a["TINV_GRID"] * P["CapacityPerDollar_Grid"]
    Grid_out = GridCap_s * P["DeprRate_Grid"]
    dGridCap = Grid_in - Grid_out

    CULT_in = P["alpha_CULT"] * COWN_in * (1 - CULT_s)
    CULT_out = P["delta_CULT"] * CULT_s
    dCULT = CULT_in - CULT_out

    TRAV_in = (
        P["alpha_TRAV_AV"] * AV_s
        + P["alpha_TRAV_MAAS"] * MAAS_s
        + P["alpha_TRAV_REG"] * P["Regulation_quality"]
        + P["alpha_TRAV_MEDIA"] * max(0.0, P["Media_tone"])
    ) * (1 - TRAV_s)
    TRAV_out = P["beta_TRAV_ACC"] * a["ACC_R"] * TRAV_s
    dTRAV = TRAV_in - TRAV_out

    return np.array([
        dPOP, dGRP, dEMP, dPARK, dUA, dCOWN,
        dEV, dAV, dV2X, dMAAS,
        dPT_cap, dGridCap, dCULT, dTRAV
    ])


def _integrate_rk4(func, t0, t1, y0, params, dt=0.25, t_eval=None):
    """Классический явный метод Рунге–Кутты 4-го порядка с фиксированным шагом dt.

    Соответствует методу интегрирования, заявленному в тексте ВКР (RK4, Δt = 0.25).
    Интегрирование ведётся по внутренней равномерной сетке с шагом dt, а значения
    в точках t_eval получаются линейной интерполяцией (стоки между узлами шага
    меняются практически линейно при таком мелком шаге).
    Возвращает объект с полями .t, .y, .success, .message — совместимо с solve_ivp.
    """
    n_steps = int(math.ceil((t1 - t0) / dt))
    ts = t0 + dt * np.arange(n_steps + 1)
    ts[-1] = t1  # гарантируем точное попадание в правый конец интервала
    ys = np.zeros((len(y0), n_steps + 1), dtype=float)
    ys[:, 0] = y0
    y = np.array(y0, dtype=float)

    for i in range(n_steps):
        t = ts[i]
        h = ts[i + 1] - ts[i]
        k1 = np.asarray(func(t, y, params), dtype=float)
        k2 = np.asarray(func(t + 0.5 * h, y + 0.5 * h * k1, params), dtype=float)
        k3 = np.asarray(func(t + 0.5 * h, y + 0.5 * h * k2, params), dtype=float)
        k4 = np.asarray(func(t + h, y + h * k3, params), dtype=float)
        y = y + (h / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)
        ys[:, i + 1] = y

    if not np.all(np.isfinite(ys)):
        return _SolLike(ts, ys, success=False,
                        message="RK4: обнаружены NaN/Inf при интегрировании")

    if t_eval is not None:
        y_eval = np.vstack([
            np.interp(t_eval, ts, ys[k, :]) for k in range(ys.shape[0])
        ])
        return _SolLike(np.asarray(t_eval, dtype=float), y_eval, success=True, message="RK4 OK")

    return _SolLike(ts, ys, success=True, message="RK4 OK")


class _SolLike:
    """Минимальная обёртка результата интегрирования, совместимая с solve_ivp."""
    def __init__(self, t, y, success, message):
        self.t = t
        self.y = y
        self.success = success
        self.message = message


def simulate(params=None, years=30, n_output=121, method="LSODA",
             rtol=1e-6, atol=1e-9, y0_override=None, dt=0.25):
    """Прогон модели.

    method:
        "RK4"  — явный Рунге–Кутта 4-го порядка с фиксированным шагом dt (по умолч. 0.25),
                  как заявлено в тексте ВКР;
        иные   — передаются в scipy.integrate.solve_ivp ("LSODA", "RK45", ...).
    """
    if params is None:
        params = P

    y0 = initial_state() if y0_override is None else np.array(y0_override, dtype=float)
    t_eval = np.linspace(0, years, n_output)

    if str(method).upper() == "RK4":
        sol = _integrate_rk4(f, 0.0, float(years), y0, params, dt=dt, t_eval=t_eval)
    else:
        sol = solve_ivp(
            f, [0, years], y0,
            method=method,
            t_eval=t_eval,
            args=(params,),
            rtol=rtol,
            atol=atol,
            max_step=0.5,
        )

    if not sol.success:
        raise RuntimeError(f"integration failed ({method}): {sol.message}")

    stocks = {name: sol.y[i] for i, name in enumerate(STOCKS)}

    aux_keys = [
        "WFH", "INC", "DENS", "ECOM", "CONG", "VMT", "EffRoadVMT",
        "MS_A", "MS_PT", "MS_RH", "MS_BK", "MS_W",
        "TT_A", "TT_PT", "TT_RH", "HABM", "AQ", "CO2", "ACC_R", "GRID",
        "TRIPS", "PEAK", "RCAP", "PTCR", "ACC_jobs",
        "TINV_PT", "TINV_road", "TINV_digital", "TINV_bike", "TINV_GRID",
        "TINV_common", "FREV", "EV_gen", "FF_spd",
        "GRP_in", "GRP_out", "COWN_des", "PARK_eff",
        "AutoVMT", "PTVMT", "FareRH", "BusLane_eff"
    ]
    aux = {k: np.zeros(n_output) for k in aux_keys}

    for j in range(n_output):
        a = compute_aux(sol.t[j], sol.y[:, j], params)
        for k in aux_keys:
            if k in a:
                aux[k][j] = a[k]

    aux["COWN_desired"] = aux["COWN_des"]
    aux["GRP_InFlow"] = aux["GRP_in"]
    aux["GRP_OutFlow"] = aux["GRP_out"]
    aux["FF_speed"] = aux["FF_spd"]

    return sol.t, stocks, aux


if __name__ == "__main__":
    T, S, O = simulate(P, years=30)

    print("=== Результаты BAU-сценарий v2.1 (solve_ivp), t=0 → t=30 ===")
    for label, arr in [
        ("ВРП, млрд$/год", S["GRP"]),
        ("Население, млн", S["POP"]),
        ("Занятость, млн", S["EMP"]),
        ("COWN, авт/1000", S["COWN"]),
        ("EV доля", S["EV"]),
        ("AV доля", S["AV"]),
        ("Загруженность CONG", O["CONG"]),
        ("TT_A, мин", O["TT_A"]),
        ("VMT, млн км/д", O["VMT"]),
        ("CO2, млн т/год", O["CO2"]),
    ]:
        print(f"  {label:25s}: {arr[0]:.3f} → {arr[-1]:.3f}")